version: "3"

services:
  movie-app:
    image: movie-app
    build: .
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DBNAME}
      - POSTGRES_HOST=postgres-movie-app
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis-todo-app
      - REDIS_PORT=6379
    depends_on:
      - postgres-movie-app
      - redis-todo-app

  postgres-movie-app:
    image: postgres
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}

  redis-todo-app:
    image: redis